import { useEffect } from 'react'
import { useFormState } from 'react-hook-form'
import type { Control, UseFormSetValue, UseFormWatch } from 'react-hook-form'
import { Plus } from 'lucide-react'

import type { Category } from '@/features/categories/types'
import type { KeywordSet, PostFormValues } from '@/features/posts/types'
import { MediaPickerField } from '@/components/common/MediaPickerDialog'
import { KeywordSetPickerField } from './KeywordSetPickerField'
import { TextEditorField } from '@/components/common/TextEditor'
import { LANGUAGE_OPTIONS } from '@/constants/languages'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { DatePicker } from '@/components/ui/date-picker'
import { FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { SearchableSelect } from '@/components/common/SearchableSelect'
import { Textarea } from '@/components/ui/textarea'

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
}

type PostFormSectionsProps = {
  control: Control<PostFormValues>
  watch: UseFormWatch<PostFormValues>
  setValue: UseFormSetValue<PostFormValues>
  /** When true, slug preview follows title changes (create mode). False keeps existing slug (edit mode). */
  autoSlug?: boolean
  categories?: Category[]
  defaultKeywordSets?: KeywordSet[]
  canCreateKeywordSet?: boolean
  canUpdateKeywordSet?: boolean
  canDeleteKeywordSet?: boolean
  canPublish?: boolean
  canCreateCategory?: boolean
  onCreateCategoryClick?: () => void
}

export function PostFormSections({
  control,
  watch,
  setValue,
  autoSlug = false,
  categories = [],
  defaultKeywordSets,
  canCreateKeywordSet = false,
  canUpdateKeywordSet = false,
  canDeleteKeywordSet = false,
  canPublish = false,
  canCreateCategory = false,
  onCreateCategoryClick,
}: PostFormSectionsProps) {
  const title = watch('title')
  const { dirtyFields } = useFormState({ control })

  useEffect(() => {
    if (!autoSlug || !dirtyFields.title) return
    setValue('slug', slugify(title ?? ''), { shouldValidate: false })
  }, [title, setValue, autoSlug, dirtyFields.title])

  return (
    <>
      <Card className="border-border shadow-none">
        <CardHeader className="pb-4">
          <CardTitle className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
            Content
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <FormField
              control={control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>
                    Title <span className="text-destructive">*</span>
                  </FormLabel>
                  <FormControl>
                    <Input placeholder="Post title" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="slug"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Slug</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      value={field.value ?? ''}
                      disabled
                      placeholder="Auto-generated by server"
                      className="cursor-not-allowed opacity-60"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {canPublish ? (
              <FormField
                control={control}
                name="status"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      Status <span className="text-destructive">*</span>
                    </FormLabel>
                    <SearchableSelect
                      value={field.value ?? ''}
                      onValueChange={field.onChange}
                      options={[
                        { label: 'Draft', value: 'draft' },
                        { label: 'Published', value: 'published' },
                        { label: 'Trash', value: 'trash' },
                      ]}
                      placeholder="Select status"
                    />
                    <FormMessage />
                  </FormItem>
                )}
              />
            ) : null}
            <FormField
              control={control}
              name="lang"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Language</FormLabel>
                  <SearchableSelect
                    value={field.value ?? undefined}
                    onValueChange={(v) => field.onChange(v)}
                    options={LANGUAGE_OPTIONS}
                    placeholder="Select language"
                    searchPlaceholder="Search language…"
                  />
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="category_id"
              render={({ field }) => (
                <FormItem>
                  <div className="flex items-center justify-between gap-2">
                    <FormLabel>Category</FormLabel>
                    {canCreateCategory && onCreateCategoryClick ? (
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="gap-1 h-[14px] p-0! px-2 text-xs text-red-400 hover:text-foreground"
                        onClick={onCreateCategoryClick}
                      >
                        <Plus className="w-3" />
                        Add
                      </Button>
                    ) : null}
                  </div>
                  <SearchableSelect
                    value={field.value ? String(field.value) : '__none__'}
                    onValueChange={(v) => field.onChange(v === '__none__' ? null : Number(v))}
                    options={[
                      ...categories.map((cat) => ({ label: cat.name, value: String(cat.id) })),
                    ]}
                    placeholder="Select category"
                  />
                  <FormMessage />
                </FormItem>
              )}
            />

            {canPublish ? (
              <FormField
                control={control}
                name="published_at"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Published At</FormLabel>
                    <FormControl>
                      <DatePicker
                        value={field.value ?? null}
                        onChange={field.onChange}
                        placeholder="Pick a date"
                        className="w-full"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            ) : null}
            {/* add keyword here field */}
          </div>
          <div className="grid grid-cols-1 items-start gap-4 sm:grid-cols-2">
            <FormField
              control={control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Description</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Short description…"
                      className="resize-none"
                      rows={3}
                      {...field}
                      value={field.value ?? ''}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={control}
              name="note"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Note</FormLabel>
                  <FormControl>
                    <Textarea
                      maxLength={255}
                      rows={3}
                      className="resize-none"
                      {...field}
                      value={field.value ?? ''}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>
          <KeywordSetPickerField
            control={control}
            name="keyword_set_ids"
            defaultItems={defaultKeywordSets}
            canCreate={canCreateKeywordSet}
            canUpdate={canUpdateKeywordSet}
            canDelete={canDeleteKeywordSet}
          />
          <MediaPickerField
            control={control}
            name="feature_media"
            label="Feature Image"
            accept="image/*"
            directory="media/posts"
            placeholder="Pick a feature image…"
          />
          <TextEditorField
            control={control}
            name="content"
            label="Content"
            placeholder="Post content…"
            minHeight="320px"
            directory="media/posts"
          />
        </CardContent>
      </Card>
    </>
  )
}
